### ISSUE TITLE
关于讨论群

### ISSUE THREAD

**Issue by qdsang** [domeos/server#15]
官方有组建讨论组吗？ 
或者开通 https://gitter.im/

自己建的兴趣交流QQ群： 99276811

**Comment by fridayis** [comment]
@qdsang 
由于产品还在快速迭代和开发中，目前还没有组建公开的DomeOS交流群和社区，之后我们会考虑。目前有问题可以在github上留言，我们会尽快回复

**Comment by qdsang** [comment]
@fridayis 什么时候能提供0.2一键安装脚本？

**Comment by fridayis** [comment]
官方讨论群：257691628
0.2的一键安装脚本正在更新，预计下周发布
