### ISSUE TITLE
可否基于现有的k8s部署domeos

### ISSUE THREAD

**Issue by mysterytree** [domeos/server#16]
生产上已经跑了k8s 
如何在尽量少的改动下上domeos

**Comment by fridayis** [comment]
@mysterytree 可以，在DomeOS的集群管理中直接添加对应集群即可，不影响已有pod

**Comment by mysterytree** [comment]
@fridayis 独立安装demoos在把现有集群添加进去吗？  竟然可以这样？

**Comment by mysterytree** [comment]
@fridayis 还有 如果是k8s on mesos 的集群也可以集成吗

**Comment by fridayis** [comment]
domeos只与k8s api server通信，添加现有集群没问题，k8s on mesos没有了解过实现方案，只要能提供k8s api server地址即可。

**Comment by mysterytree** [comment]
@fridayis 那应该可以兼容  另外如果我用的是之前装好的k8s集群 现在是不是只需要把domeos的server跑起来就好了  也就是说server模块可以独立安装吗

**Comment by fridayis** [comment]
是的，独立安装没问题
server依赖于mysql，启动server和mysql即可

**Comment by mysterytree** [comment]
@fridayis 感谢解答  我试试看 有问题再来
